env:
  browser: true
  es2021: true
extends: airbnb-base
plugins:
  - import
parserOptions:
  sourceType: module
  allowImportExportEverywhere: true
  ecmaVersion: latest
rules:
  no-console: 0
  import/extensions: 'off'
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]